name: kjnjkna

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: Setup jave
              uses: actions/setup-java@v4
              with: 
                java-version: '17'
                distribution: 'temurin'

            - name: Build Code
              working-directory: axisbank
              run: mvn clean package

            - name: Build and test
              working-directory: axisbank
              run: mvn clean test

            - name: Build Image into Docker
            #   working-directory: axisbank
              run: docker build -t axisbank-app:${GITHUB_RUN_NUMBER} -f axisbank/Dockerfile axisbank
      
            - name: Check image file
              run: docker image ls
      
            - name: Docker Login
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
            - name: Tag name
              run: docker tag axisbank-app:${{ github.run_number }} rohitkumar4praja/axisbank-app:${{ github.run_number }}
      
            - name: push Image
              run: docker push rohitkumar4praja/axisbank-app:${{ github.run_number }}
            