name: kjnjkna

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

            - name: checkout code
              uses: actions/checkout@v4

            - name: Setup jave
              uses: actions/setup-java@v4
              with: 
                version: '17'
                distribution: 'temurin'

            - name: Build and test
              run: mvn clean test

            